using Blackbird.Applications.Sdk.Utils.Sdk.DataSourceHandlers;

namespace Apps.Storyblok.DataSourceHandlers.EnumHandlers;

public class LanguageDataHandler : EnumDataHandler
{
    protected override Dictionary<string, string> EnumValues => new()
    {
        { "af", "Afrikaans" },
        { "sq", "Albanian" },
        { "ar", "Arabic" },
        { "ar_dz", "Arabic (Algeria)" },
        { "ar_bh", "Arabic (Bahrain)" },
        { "ar_eg", "Arabic (Egypt)" },
        { "ar_iq", "Arabic (Iraq)" },
        { "ar_jo", "Arabic (Jordan)" },
        { "ar_kw", "Arabic (Kuwait)" },
        { "ar_lb", "Arabic (Lebanon)" },
        { "ar_ly", "Arabic (Libya)" },
        { "ar_ma", "Arabic (Morocco)" },
        { "ar_om", "Arabic (Oman)" },
        { "ar_qa", "Arabic (Qatar)" },
        { "ar_sa", "Arabic (Saudi Arabia)" },
        { "ar_sy", "Arabic (Syria)" },
        { "ar_tn", "Arabic (Tunisia)" },
        { "ar_ae", "Arabic (U.A.E.)" },
        { "ar_ye", "Arabic (Yemen)" },
        { "an", "Aragonese" },
        { "hy", "Armenian" },
        { "as", "Assamese" },
        { "ast", "Asturian" },
        { "az", "Azerbaijani" },
        { "eu", "Basque" },
        { "be", "Belarusian" },
        { "bn", "Bengali" },
        { "bs", "Bosnian" },
        { "br", "Breton" },
        { "bg", "Bulgarian" },
        { "my", "Burmese" },
        { "ca", "Catalan" },
        { "ch", "Chamorro" },
        { "ce", "Chechen" },
        { "zh", "Chinese" },
        { "zh_hk", "Chinese (Hong Kong)" },
        { "zh_cn", "Chinese (PRC)" },
        { "zh_sg", "Chinese (Singapore)" },
        { "zh_tw", "Chinese (Taiwan)" },
        { "cv", "Chuvash" },
        { "co", "Corsican" },
        { "cr", "Cree" },
        { "hr", "Croatian" },
        { "cs", "Czech" },
        { "da", "Danish" },
        { "nl", "Dutch" },
        { "nl_be", "Dutch (Belgian)" },
        { "en", "English" },
        { "en_au", "English (Australia)" },
        { "en_bz", "English (Belize)" },
        { "en_ca", "English (Canada)" },
        { "en_ie", "English (Ireland)" },
        { "en_jm", "English (Jamaica)" },
        { "en_nz", "English (New Zealand)" },
        { "en_ph", "English (Philippines)" },
        { "en_za", "English (South Africa)" },
        { "en_tt", "English (Trinidad & Tobago)" },
        { "en_gb", "English (United Kingdom)" },
        { "en_us", "English (United States)" },
        { "en_zw", "English (Zimbabwe)" },
        { "eo", "Esperanto" },
        { "et", "Estonian" },
        { "fo", "Faeroese" },
        { "fa", "Farsi" },
        { "fj", "Fijian" },
        { "fi", "Finnish" },
        { "fr", "French" },
        { "fr_be", "French (Belgium)" },
        { "fr_ca", "French (Canada)" },
        { "fr_fr", "French (France)" },
        { "fr_lu", "French (Luxembourg)" },
        { "fr_mc", "French (Monaco)" },
        { "fr_ch", "French (Switzerland)" },
        { "fy", "Frisian" },
        { "fur", "Friulian" },
        { "gd", "Gaelic (Scots)" },
        { "gd_ie", "Gaelic (Irish)" },
        { "gl", "Galacian" },
        { "ka", "Georgian" },
        { "de", "German" },
        { "de_at", "German (Austria)" },
        { "de_de", "German (Germany)" },
        { "de_li", "German (Liechtenstein)" },
        { "de_lu", "German (Luxembourg)" },
        { "de_ch", "German (Switzerland)" },
        { "el", "Greek" },
        { "gu", "Gujurati" },
        { "ht", "Haitian" },
        { "he", "Hebrew" },
        { "hi", "Hindi" },
        { "hu", "Hungarian" },
        { "is", "Icelandic" },
        { "id", "Indonesian" },
        { "iu", "Inuktitut" },
        { "ga", "Irish" },
        { "it", "Italian" },
        { "it_ch", "Italian (Switzerland)" },
        { "ja", "Japanese" },
        { "kn", "Kannada" },
        { "ks", "Kashmiri" },
        { "kk", "Kazakh" },
        { "km", "Khmer" },
        { "ky", "Kirghiz" },
        { "tlh", "Klingon" },
        { "ko", "Korean" },
        { "ko_kp", "Korean (North Korea)" },
        { "ko_kr", "Korean (South Korea)" },
        { "la", "Latin" },
        { "lv", "Latvian" },
        { "lt", "Lithuanian" },
        { "lb", "Luxembourgish" },
        { "mk", "FYRO Macedonian" },
        { "ms", "Malay" },
        { "ml", "Malayalam" },
        { "mt", "Maltese" },
        { "mi", "Maori" },
        { "mr", "Marathi" },
        { "mo", "Moldavian" },
        { "nv", "Navajo" },
        { "ng", "Ndonga" },
        { "ne", "Nepali" },
        { "no", "Norwegian" },
        { "nb", "Norwegian (Bokmal)" },
        { "nn", "Norwegian (Nynorsk)" },
        { "oc", "Occitan" },
        { "or", "Oriya" },
        { "om", "Oromo" },
        { "fa_ir", "Persian/Iran" },
        { "pl", "Polish" },
        { "pt", "Portuguese" },
        { "pt_br", "Portuguese (Brazil)" },
        { "pa", "Punjabi" },
        { "pa_in", "Punjabi (India)" },
        { "pa_pk", "Punjabi (Pakistan)" },
        { "qu", "Quechua" },
        { "rm", "Rhaeto_Romanic" },
        { "ro", "Romanian" },
        { "ro_mo", "Romanian (Moldavia)" },
        { "ru", "Russian" },
        { "ru_mo", "Russian (Moldavia)" },
        { "sz", "Sami (Lappish)" },
        { "sg", "Sango" },
        { "sa", "Sanskrit" },
        { "sc", "Sardinian" },
        { "sd", "Sindhi" },
        { "si", "Singhalese" },
        { "sr", "Serbian" },
        { "sk", "Slovak" },
        { "sl", "Slovenian" },
        { "so", "Somani" },
        { "sb", "Sorbian" },
        { "es", "Spanish" },
        { "es_ar", "Spanish (Argentina)" },
        { "es_bo", "Spanish (Bolivia)" },
        { "es_cl", "Spanish (Chile)" },
        { "es_co", "Spanish (Colombia)" },
        { "es_cr", "Spanish (Costa Rica)" },
        { "es_do", "Spanish (Dominican Republic)" },
        { "es_ec", "Spanish (Ecuador)" },
        { "es_sv", "Spanish (El Salvador)" },
        { "es_gt", "Spanish (Guatemala)" },
        { "es_hn", "Spanish (Honduras)" },
        { "es_mx", "Spanish (Mexico)" },
        { "es_ni", "Spanish (Nicaragua)" },
        { "es_pa", "Spanish (Panama)" },
        { "es_py", "Spanish (Paraguay)" },
        { "es_pe", "Spanish (Peru)" },
        { "es_pr", "Spanish (Puerto Rico)" },
        { "es_es", "Spanish (Spain)" },
        { "es_uy", "Spanish (Uruguay)" },
        { "es_ve", "Spanish (Venezuela)" },
        { "sx", "Sutu" },
        { "sw", "Swahili" },
        { "sv", "Swedish" },
        { "sv_fi", "Swedish (Finland)" },
        { "sv_sv", "Swedish (Sweden)" },
        { "ta", "Tamil" },
        { "tt", "Tatar" },
        { "te", "Teluga" },
        { "th", "Thai" },
        { "tig", "Tigre" },
        { "ts", "Tsonga" },
        { "tn", "Tswana" },
        { "tr", "Turkish" },
        { "tk", "Turkmen" },
        { "uk", "Ukrainian" },
        { "hsb", "Upper Sorbian" },
        { "ur", "Urdu" },
        { "ve", "Venda" },
        { "vi", "Vietnamese" },
        { "vo", "Volapuk" },
        { "wa", "Walloon" },
        { "cy", "Welsh" },
        { "xh", "Xhosa" },
        { "ji", "Yiddish" },
        { "zu", "Zulu" }
    };
}